### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by teod** [zoobestik/csso-webpack-plugin#11]
### Specifications
- **CSSO Plugin version**: v1.0.0-beta.10
- **Webpack version**: v4.1.1

**/cc** @zoobestik

**Comment by zoobestik** [comment]
@teod, thanks for your issue. Can you provide more information about compatibility problems?

I tried `v1.0.0-beta.10` with **webpack 4.1.1**:
* [**extract-text-webpack-plugin@^4.0.0-beta.0**](https://github.com/zoobestik/stackoverflow-45870309/tree/webpack4)
* [**mini-css-extract-plugin@^0.2.0**](https://github.com/zoobestik/stackoverflow-45870309/tree/webpack4-mini)

both look fine.

**Comment by zoobestik** [comment]
Help me anyone for additional information.
