### ISSUE TITLE
Webpack 4.x deprecation warning

### ISSUE THREAD

**Issue by the-spyke** [zoobestik/csso-webpack-plugin#13]
As a developer I want to use this plug-in with Webpack 4.5.0. But I see a warning in console:

```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**/cc** @zoobestik

**Comment by zoobestik** [comment]
Thanks for your report!
@the-spyke, it will be fixed with next release: https://github.com/zoobestik/csso-webpack-plugin/pull/14

**Comment by zoobestik** [comment]
New version released:
https://github.com/zoobestik/csso-webpack-plugin/releases/tag/v1.0.0-beta.12
