### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by Finesse** [zoobestik/csso-webpack-plugin#22]
Hi! CSSO version 4 has been released. Could you please update the dependency of this package?

Also the `async` dependency can be discarded because Node.js supports Promises since version 0.12 and `async/await` since version 7.6.

**Comment by zoobestik** [comment]
Thank you, it will be soon.

**Comment by zoobestik** [comment]
**Fixed**, try new release [v2.0.0-beta.1](https://github.com/zoobestik/csso-webpack-plugin/releases/tag/v2.0.0-beta.1).
Let me know if you will have problems.

**Comment by Finesse** [comment]
@zoobestik It works fine. Thank you!
