### ISSUE TITLE
core-js should be a dependency

### ISSUE THREAD

**Issue by bpierre** [zoobestik/csso-webpack-plugin#28]
[core-js is set as a `devDependency`](https://github.com/zoobestik/csso-webpack-plugin/blob/ef0960a0ffa368a783311b8d66876984f7b11d57/package.json#L59), but it is being imported [at runtime](https://unpkg.com/browse/csso-webpack-plugin@2.0.0-beta.2/lib/index.js#L6).

Moving it to the `dependencies` should fix the issue.

**Comment by zoobestik** [comment]
Thanks for report!
Fixed in [2.0.0-beta.3](https://github.com/zoobestik/csso-webpack-plugin/releases/tag/v2.0.0-beta.3)
