### ISSUE TITLE
core-js devDependencies  

### ISSUE THREAD

**Issue by keepresolve** [zoobestik/csso-webpack-plugin#29]
core-js ^3.10.0      

![image](https://user-images.githubusercontent.com/29271171/113983862-02308400-987d-11eb-8fdf-9bf056c90895.png)
![image](https://user-images.githubusercontent.com/29271171/113983992-2d1ad800-987d-11eb-9f8c-a0421d5df7ed.png)

**Comment by zoobestik** [comment]
Duplicate #28.
Closed in [2.0.0-beta.3](https://github.com/zoobestik/csso-webpack-plugin/releases/tag/v2.0.0-beta.3)
