### ISSUE TITLE
Add a way to create scopes configuration using the input CSS

### ISSUE THREAD

**Issue by gajus** [zoobestik/csso-webpack-plugin#5]
This relates to this issue https://github.com/css/csso/issues/345

I'd like to be able to create [`scopes`](https://github.com/css/csso#scopes) configuration using the input CSS, e.g.

If input CSS is:

```css
.styles___pagination-button___1dMOo.styles___next___2BxhK {}
.styles___pagination-button___1dMOo.styles___active___2sAsB {}
.styles___pagination-button___1dMOo.styles___active___2sAsB:hover {}

```

I can use a simple function to recognize styles belonging to different modules and create scopes configuration, e.g.

```js
// Just a prototype code.

new CssoWebpackPlugin({
  createScopes: (inputCss: string) => {
    const scopes = {};

    inputCss.match(/\.(.*?)___(.*?)___[a-zA-Z0-9]+/g).forEach((className) => {
    	const moduleId = className.split('___').slice(0, 2).join('___');
      
      if (!scopes[moduleId]) {
      	scopes[moduleId] = [];
      }
      
      scopes[moduleId].push(className);
    });

    return Object.values(scopes);
  }
})

```

**Comment by gajus** [comment]
@zoobestik Any chance of you picking up this issue?

Otherwise, any chance of adding me as a colab to the github/ npm project?

**Comment by zoobestik** [comment]
@gajus, yep, I can implement the feature if you need it.

I create PR #6  for resolve this issue. 
I will shipped it to **npm** ASAP if it solves your problem.

**P.S.** Sorry for the delay.

**Comment by gajus** [comment]
No rush. Thank you for a rapid follow up.

**Comment by zoobestik** [comment]
@gajus, ok,

I take some time for research your case again and, i think, regexp isn't safety for get `moduleId`.
It's can match id for file name into `background: url(...)` property, for example.
What do you think about this case?

Workaround for your issue with `beforeCompress`:
```javascript
const csso = require('csso');

const getScopes = (ast, getModuleID) => {
    const scopes = {};
    csso.syntax.walk(ast, node => {
        if (node.type === 'ClassSelector') {
            const moduleId = getModuleID(node.name);
            if (moduleId) {
                if (!scopes[moduleId]) scopes[moduleId] = [];
                scopes[moduleId].push(className);
            }
        }
    });
    return Object.values(scopes);
};

const getId = className => { /* ....generate module id py prefix... */ };

new CssoWebpackPlugin({
    beforeCompress(ast, options) {
        options.usage = { scopes: getScopes(ast, getId) };
    },
});
```
Generate scopes with **ast** should be better – faster and safety.

**Comment by gajus** [comment]
> Generate scopes with ast should be better – faster and safety.

Yup, that sounds like a good suggestion.

The regex example was just a prototype. I would have used ast parser. You just did the hard work. :-) 👍

**Comment by zoobestik** [comment]
Thanks, do you still need function for generate scopes inside plugin or `beforeCompress`–solution is full enough?

**Comment by gajus** [comment]
Ah! I didn't realize that `beforeCompress` comes from CSSO API. It is perfect and more than enough.

Sorry, my oversight.

**Comment by zoobestik** [comment]
No problem, if sometime you will shere with me how many bites it's reduced in your bundles, i will happy! :)

**Comment by gajus** [comment]
Sadly, nothing interesting to report. Reduction from 107K to 104K.

**Comment by gajus** [comment]
@zoobestik Might find this interesting https://medium.com/@gajus/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b

**Comment by lahmatiy** [comment]
> Sadly, nothing interesting to report. Reduction from 107K to 104K.

@gajus It's about 3%, more than nothing ;) The result depends on CSS structure and a bundle size. When I applied scopes for our project it [saves about 26%](https://www.slideshare.net/basisjs/csso-compress-css-english-version/76) and [61% with class name renaming](https://www.slideshare.net/basisjs/csso-compress-css-english-version/81).
Also CSSO doesn't do all possible optimisations on restructing at the moment, more is comming. Probably the result will be improved in the future.
