### ISSUE TITLE
sourceMap not working with webpack 3

### ISSUE THREAD

**Issue by Koniksan** [zoobestik/csso-webpack-plugin#7]
sourceMap.options : true , inline , source-map not working at all with webpack 3

**Comment by zoobestik** [comment]
@Koniksan, can you provide me more information about your issue and current setup: `webpack.config.js`; `node`, `npm` and packages versions? Do you use [devtool](https://webpack.github.io/docs/configuration.html#devtool) option?

**P.S.** I [tried it](https://travis-ci.org/zoobestik/csso-webpack-plugin/builds/256332661) with `extract-text-webpack-plugin=3.0.0`, `webpack=3.3.0`.
It's looks good:
<img width="368" alt="screen shot 2017-07-22 at 13 06 18" src="https://user-images.githubusercontent.com/242514/28490273-92a9ed0e-6ede-11e7-8973-4d50aa1067e0.png">

**Comment by zoobestik** [comment]
Pls, reopen ticket with additional information

**Comment by Koniksan** [comment]
I will send you more info later. By the way you checked what source map generated ? 
I mean that it is generated but with wrong data inside. Maybe i am not good explain but i am trying my best )
